const data = [
  "laborum cillum et irure adipisicing dolor ipsum eu velit deserunt ipsum Lorem aute voluptate mollit mollit adipisicing reprehenderit pariatur fugiat",
  "do officia qui minim dolore adipisicing aute sint irure officia ullamco irure qui reprehenderit qui ad fugiat sint non consequat quis tempor voluptate mollit ea minim irure amet aliquip dolor qui culpa sit occaecat reprehenderit Lorem sit id cillum ad",
  "ut est ad ipsum deserunt fugiat aliqua duis laboris excepteur minim nisi commodo occaecat culpa fugiat eiusmod proident aliquip exercitation non laboris cupidatat id quis culpa non aute fugiat eu qui ex est officia adipisicing ad sit eu velit aliquip voluptate ea commodo qui eiusmod non amet in esse id sint tempor labore qui ea dolore ad non ad mollit",
  "elit id culpa ex duis et adipisicing tempor sunt labore eu sit nostrud magna pariatur nisi aliqua consectetur dolore consequat qui anim veniam dolore ad consectetur esse occaecat aute mollit eiusmod irure Lorem laboris nostrud nulla laborum cillum cillum ut anim consectetur id non ullamco anim veniam magna cupidatat ad consectetur nisi adipisicing laboris dolor qui aliqua sint officia magna nulla aliquip laboris ad cupidatat fugiat laborum eu quis voluptate ea irure id excepteur eu duis enim officia aliqua consequat",
  "ad consectetur ipsum enim ea magna excepteur elit officia cupidatat cillum aliquip ad est duis ex aliqua est culpa culpa laborum laboris eu nostrud duis quis et tempor esse quis laborum incididunt elit irure duis enim quis fugiat cupidatat proident in irure proident ullamco irure enim veniam eiusmod ea commodo mollit amet do ipsum do eiusmod consequat pariatur eu cillum cupidatat exercitation anim mollit reprehenderit laborum ex aute quis velit nostrud exercitation adipisicing deserunt ut ipsum ut cupidatat cupidatat enim eu qui cupidatat fugiat esse consectetur elit non labore nostrud elit aliquip qui pariatur deserunt laboris ex adipisicing aute aute",
];

export default data;
